config/routes.rb
Rails.application.routes.draw do
  resources :organisations
  root 'welcome#index'
  get 'welcome/index'

  devise_for :users, controllers: { registrations: "registrations" }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  belongs_to :user

  validates :name, :service_type, :description, :address, :postcode, :telephone, presence: true

  geocoded_by :postcode
  after_validation :geocode
  after_validation :reverse_geocode

  reverse_geocoded_by :latitude, :longitude do |obj,results|
    if geo = results.first
      obj.city = geo.city
      obj.country = geo.country_code
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_one :organisation

  devise :database_authenticatable, :registerable, :confirmable, 
        :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :warning, :danger, :info
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /organisations
  # GET /organisations.json
  def index
    @organisations = Organisation.all
  end

  # GET /organisations/1
  # GET /organisations/1.json
  def show
  end

  # GET /organisations/new
  def new
    @organisation = Organisation.new
  end

  # GET /organisations/1/edit
  def edit
  end

  # POST /organisations
  # POST /organisations.json
  def create
    @organisation = Organisation.new(organisation_params)

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to @organisation, notice: 'Organisation was successfully created.' }
        format.json { render :show, status: :created, location: @organisation }
      else
        format.html { render :new }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organisations/1
  # PATCH/PUT /organisations/1.json
  def update
    respond_to do |format|
      if @organisation.update(organisation_params)
        format.html { redirect_to @organisation, notice: 'Organisation was successfully updated.' }
        format.json { render :show, status: :ok, location: @organisation }
      else
        format.html { render :edit }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisations/1
  # DELETE /organisations/1.json
  def destroy
    @organisation.destroy
    respond_to do |format|
      format.html { redirect_to organisations_url, notice: 'Organisation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organisation
      @organisation = Organisation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organisation_params
      params.require(:organisation).permit(:user_id, :name, :service_type, :description, :address, :postcode, :city, :country, :telephone)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  prepend_before_action :set_minimum_password_length, only: [:new, :edit]
  prepend_before_action :require_no_authentication, only: [:new, :create, :cancel]

  # GET /resource/sign_up
  def new
    build_resource({})
    yield resource if block_given?
    respond_with resource
  end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      @organisation = Organisation.new
      @organisation.user_id = resource.id
      @organisation.save!(:validate => false)
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up)
  end


protected

  # def after_sign_up_path_for(resource)
  #   edit_profile_path(resource.profile)
  # end

  # def after_inactive_sign_up_path_for(resource)
  #   edit_profile_path(resource.profile)
  # end

private

  def sign_up_params
    params.require(:user).permit(:category, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def owner(object)
    if object.user == current_user
      true
    else
      false
    end
  end

end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close" style="margin-top:5px">×</a>
      <h5><%= value %></h5>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wecare</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>

    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>      

    </div>


  </body>
</html>

app/views/organisations/_form.html.erb
<%= simple_form_for(@organisation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :service_type, collection: ['Acute services (ACS)', 'Hyperbaric chamber services (HBC)', 'Hospice services (HPS)', 'Long-term conditions services (LTC)', ' Hospital services for people with mental health needs, and/or learning disabilities, and/or problems with substance misuse (MLS)', 'Prison healthcare services (PHS)', 'Rehabilitation services (RHS)', 'Residential substance misuse treatment/ rehabilitation services (RSM)', 'Community healthcare services (CHC)', 'Doctors consultation services (DCS)', 'Doctors treatment services (DTS)', 'Dental services (DEN)', 'Diagnostic and/or screening services (DSS)', 'Community-based services for people with a learning disability (LDC)', 'Mobile doctors services (MBS)', 'Community-based services for people with mental health needs (MHC)', 'Community-based services for people who misuse substances (SMC)', 'Urgent care services (UCS)', 'Care home services with nursing (CHN)', 'Care home services without nursing (CHS)', 'Specialist college services (SPC)', 'Domiciliary care services including those provided for children (DCC)', 'Extra care housing services (EXC)', 'Shared Lives (formerly known as Adult Placement) (SHL)', 'Supported living services (SLS)', 'Ambulance services (AMB)', 'Blood and transplant services (BTS)', 'Remote clinical advice services (RCA)'] %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :postcode %>
    <%= f.input :telephone %>
  </div>
  <hr>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/organisations/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Editing Organisation</h3>
  </div>
  <div class="panel-body">
    <%= render 'form', organisation: @organisation %>

    <%= link_to 'Show', @organisation %> |
    <%= link_to 'Back', organisations_path %>
  </div>
</div>

app/views/organisations/index.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>
  <h1>Organisations</h1>
  <hr>
  <% @organisations.each do |organisation| %>
    
    <div class="col-lg-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4><%= organisation.name %></h4>
        </div>
        <div class="panel-body">
          <p><%= organisation.service_type %></p>
          <p><%= organisation.description %></p>
          <p><%= organisation.address %></p>
          <p><%= organisation.postcode %></p>
          <p><%= organisation.city %></p>
          <p><%= organisation.telephone %></p>
          <p><%= organisation.country %></p>
        </div>
      </div>
    </div>
  <% end %>  
</div>

<%= link_to 'New Organisation', new_organisation_path %>

app/views/organisations/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">New Organisation</h3>
  </div>
  <div class="panel-body">
    <%= render 'form', organisation: @organisation %>

    <%= link_to 'Back', organisations_path %>
  </div>
</div>

app/views/organisations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @organisation.user %>
</p>

<p>
  <strong>Name:</strong>
  <%= @organisation.name %>
</p>

<p>
  <strong>Service type:</strong>
  <%= @organisation.service_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @organisation.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @organisation.address %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @organisation.postcode %>
</p>

<p>
  <strong>City:</strong>
  <%= @organisation.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @organisation.country %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @organisation.telephone %>
</p>

<%= link_to 'Edit', edit_organisation_path(@organisation) %> |
<%= link_to 'Back', organisations_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'WeCare', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Search', organisations_path %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit Settings', edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/welcome/index.html.erb
<%= link_to 'Add Organtisation', new_organisation_path, class: 'btn btn-primary' %> 